version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/todo-api
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=SOMETHING_SECRETIVE
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
    command: npm start

  mongo:
    image: mongo:6.0
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.0
    ports:
      - '6380:6379'
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
