name: Backend Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  be_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.0'
          cache: 'npm'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '6.0'

      - name: Install Dependencies
        run: npm ci

      - name: Run API Tests
        run: npm run test:ci
        env:
          CI: true
